import { defineConfig } from '@umijs/max';

export default defineConfig({
  hash: true,
  styles: ['src/global.less'],
  antd: {
    configProvider: {},
    dark: true,
    theme: {
      token: {
        colorPrimary: '#2f7df6',
        colorBgBase: '#080910',
        colorBgContainer: '#141823',
        colorBgElevated: '#1b2030',
        colorBgLayout: '#080910',
        colorBorderSecondary: 'rgba(255,255,255,0.08)',
        borderRadius: 8,
        borderRadiusLG: 8,
        fontSize: 14,
        wireframe: false,
      },
      components: {
        Card: {
          colorBgContainer: '#141823',
          borderRadiusLG: 8,
        },
        Menu: {
          colorBgContainer: 'transparent',
          colorItemBgSelected: 'rgba(47,125,246,0.18)',
        },
        Table: {
          colorBgContainer: '#141823',
          headerBg: '#1b2030',
        },
        Modal: {
          colorBgElevated: '#1b2030',
        },
        Segmented: {
          colorBgLayout: '#141823',
          borderRadiusSM: 8,
        },
      },
    },
  },
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: {
    title: 'MediaManager',
  },
  routes: [
    { path: '/login', component: './Auth/Login', layout: false },
    { path: '/setup', component: './Auth/Setup', layout: false },
    { path: '/', redirect: '/dashboard' },
    {
      name: '仪表盘',
      path: '/dashboard',
      component: './Dashboard',
      icon: 'DashboardOutlined',
    },
    {
      name: '发现',
      path: '/discover',
      component: './Discover',
      icon: 'CompassOutlined',
      access: 'canViewMedia',
    },
    { path: '/search', redirect: '/browse', hideInMenu: true },
    {
      name: '媒体浏览',
      path: '/browse',
      component: './Media/Browse',
      icon: 'AppstoreOutlined',
      access: 'canViewMedia',
    },
    {
      name: '媒体库',
      path: '/libraries',
      component: './Library/List',
      icon: 'FolderOutlined',
      access: 'canViewLibrary',
    },
    { path: '/libraries/create', component: './Library/Create', access: 'canManageLibrary' },
    { path: '/libraries/:id', component: './Library/Detail', access: 'canViewLibrary' },
    { path: '/libraries/:id/edit', component: './Library/Create', access: 'canManageLibrary' },
    {
      path: '/libraries/:id/plugins',
      component: './Library/Plugins',
      access: 'canEditLibraryPlugins',
    },
    { path: '/media/:id', component: './Media/Detail', access: 'canViewMedia' },
    { path: '/player/:id', component: './Media/Player', access: 'canPlayMedia' },
    {
      name: '标签管理',
      path: '/classification/tags',
      component: './Classification/Tags',
      icon: 'TagsOutlined',
      access: 'canManageTags',
    },
    {
      name: '分类管理',
      path: '/classification/categories',
      component: './Classification/Categories',
      icon: 'ClusterOutlined',
      access: 'canManageCategories',
    },
    {
      name: '设置',
      path: '/settings',
      component: './Settings/_layout',
      icon: 'SettingOutlined',
      access: 'canAccessSettings',
      routes: [
        { path: '/settings', component: './Settings/Index', hideInMenu: true },
        {
          path: '/settings/general',
          component: './Settings/General',
          hideInMenu: true,
          access: 'canManageSystem',
        },
        {
          path: '/settings/security',
          component: './Settings/Security',
          hideInMenu: true,
          access: 'canManageSystem',
        },
        {
          path: '/settings/media-processing',
          component: './Settings/MediaProcessing',
          hideInMenu: true,
          access: 'canManageSystem',
        },
        {
          path: '/settings/integrations',
          component: './Settings/Integrations',
          hideInMenu: true,
          access: 'canManageSystem',
        },
        {
          path: '/settings/appearance',
          component: './Settings/Appearance',
          hideInMenu: true,
          access: 'canManageSystem',
        },
        {
          path: '/settings/ai',
          component: './Settings/Ai',
          hideInMenu: true,
          access: 'canManageSystem',
        },
        {
          path: '/settings/rules',
          component: './Settings/Rules',
          hideInMenu: true,
          access: 'canManageCategories',
        },
        {
          path: '/settings/tasks',
          component: './Settings/Tasks',
          hideInMenu: true,
          access: 'canViewTasks',
        },
        {
          path: '/settings/users',
          component: './Users/Management',
          hideInMenu: true,
          access: 'canManageUsers',
        },
        {
          path: '/settings/logs',
          component: './System/Logs',
          hideInMenu: true,
          access: 'canManageSystem',
        },
        {
          path: '/settings/scrape-schedules',
          component: './Scrape/Schedules',
          hideInMenu: true,
          access: 'canManageLibrary',
        },
        {
          path: '/settings/plugins',
          component: './Settings/Plugins',
          hideInMenu: true,
          access: 'canEditLibraryPlugins',
        },
        { path: '/settings/profile', component: './Settings/Profile', hideInMenu: true },
      ],
    },
    { path: '/users', redirect: '/settings/users', hideInMenu: true },
    { path: '/system/logs', redirect: '/settings/logs', hideInMenu: true },
    { path: '/scrape/schedules', redirect: '/settings/scrape-schedules', hideInMenu: true },
    {
      name: '回收站',
      path: '/recycle-bin',
      component: './RecycleBin',
      icon: 'DeleteOutlined',
      access: 'canViewRecycleBin',
    },
    {
      name: 'AI 审核',
      path: '/intelligence/review',
      component: './Intelligence/Review',
      icon: 'RobotOutlined',
      access: 'canEditMetadata',
    },
  ],
  proxy: {
    '/api/v1': {
      target: 'http://localhost:8080',
      changeOrigin: true,
    },
  },
  npmClient: 'npm',
});
