CREATE TABLE classification_rule (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(128) NOT NULL,
    rule_type VARCHAR(32) NOT NULL,
    expression TEXT NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_value VARCHAR(256) NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    priority INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
